name: test and push to docker
on:
  push:
    branches: main
jobs:
  test:
    runs-on: ubuntu-latest
    name: test and push to dockerhub
    env:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: Checkout code
          uses: actions/checkout@v2
      - name: test
        run: ./test.sh