name: test and push to docker
on:
  push:
    branches: main
jobs:
  test:
    runs-on: ubuntu-latest
    name: test and push to dockerhub
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: test
        run: ./test.sh
      - name: publish to docker
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          docker login -u $DOCKERHUB_USER -p $DOCKERHUB_TOKEN
      - name: build
        run: |
          docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USER }}/rest-stub:$(date +%s)
      - name: push
        run: |
          docker push ${{ secrets.DOCKERHUB_USER }}/rest-stub:$(date +%s)